using SkoffinFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WpfApp3
{
	/// <summary>
	/// Interaction logic for MainWindow.xaml
	/// </summary>
	public partial class MainWindow : Window
	{
		public MainWindow()
		{
			InitializeComponent();
		}

		public void TextBox_GotFocus(object sender, RoutedEventArgs e)
		{
			TextBox tb = (TextBox)sender;
			tb.Text = string.Empty;
			tb.FontStyle = FontStyles.Normal;
			tb.GotFocus -= TextBox_GotFocus;
		}

		private void GenerateFiles(object sender, RoutedEventArgs e)
		{
			//Hlöðum inn grunngildum fyrir DatabaseMockup-ið, þetta er til þess að forritið viti hvar gagnagrunnsskilgreiningarnar eru
			DatabaseMockup.InitializeDatabaseMockup(baseFolderPath.Text);

			//Skilgreinum viðvörunina sem á að birtast í öllum auto generated file-um
			string fileAutoGenerationWarningText = "Autogenerated File - Warning: All modifications will be overwritten. File generated at: " + DateTime.UtcNow;

			//Setjum upp background worker til að sjá um að keyra löngu skipunina sem generate-ar kóðann
			BackgroundWorker worker = new BackgroundWorker();
			worker.DoWork += (o, ea) =>
			{
				//no direct interaction with the UI is allowed from this method
				this.Dispatcher.Invoke(() =>
				{
					//Hreinsum möppur og útbúum file-a
					ViewGenerator.GenerateViews(baseFolderPath.Text + pathToViews.Text, fileAutoGenerationWarningText);
					ViewModelGenerator.GenerateViewModels(baseFolderPath.Text + pathToViewModels.Text, fileAutoGenerationWarningText);
					ControllerGenerator.GenerateControllers(baseFolderPath.Text + pathToControllers.Text, fileAutoGenerationWarningText);
				});
			};
			worker.RunWorkerCompleted += (o, ea) =>
			{
				//work has completed. you can now interact with the UI
				busyIndicator.IsBusy = false;
			};
			//TODO: Þetta er nóg til þess að gera view-ið greyed out á meðan við erum að vinna, en sýnir ekki loading bar-ið sem er þarna á bakvið. Vil finna út af hverju ekki, hefur sennilega eitthvað að gera með þræði
			 busyIndicator.IsBusy = true;

			//Setjum worker-inn í gang sem keyrir langa process-ið
			worker.RunWorkerAsync();
		}

		private void DeleteFiles(object sender, RoutedEventArgs e)
		{
			//Hreinsum möppur án þess að generate-a file-a
			ViewGenerator.DeleteViews(baseFolderPath.Text + pathToViews.Text);
			ViewModelGenerator.DeleteViewModels(baseFolderPath.Text + pathToViewModels.Text);
			ControllerGenerator.DeleteControllers(baseFolderPath.Text + pathToControllers.Text);
		}
	}
}
